# Generated by Django 4.0.5 on 2022-06-06 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_content_name_nikki_content_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nikki',
            old_name='create_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='nikki',
            old_name='content_detail',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='nikki',
            old_name='content_title',
            new_name='title',
        ),
    ]
