# Generated by Django 4.0.5 on 2022-06-07 01:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_create_date_nikki_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nikki',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 7, 1, 39, 25, 675714, tzinfo=utc)),
        ),
    ]
